--- Makefile.orig	2019-02-05 04:42:41.217657137 -0500
+++ Makefile	2019-02-05 04:51:11.576264269 -0500
@@ -723,6 +723,14 @@
 endif # HAS_EMBEDDED_OPENSSL_ALPN
 endif # HAS_SYSTEM_OPENSSL_ALPN
 
+ifeq ($(EMBED_OPENSSL),false)
+OPENSSL_DEP += GOPATH/grpc/third_party/openssl-1.1.0g/libssl.a GOPATH/grpc/third_party/openssl-1.1.0g/libcrypto.a
+OPENSSL_MERGE_LIBS += GOPATH/grpc/third_party/openssl-1.1.0g/libssl.a GOPATH/grpc/third_party/openssl-1.1.0g/libcrypto.a
+OPENSSL_MERGE_OBJS += $(wildcard GOPATH/grpc/third_party/openssl-1.1.0g/grpc_obj/*.o)
+# need to prefix these to ensure overriding system libraries
+CPPFLAGS := -IGOPATH/grpc/third_party/openssl-1.1.0g/include $(CPPFLAGS)
+endif
+
 OPENSSL_DEP :=
 OPENSSL_MERGE_LIBS :=
 ifeq ($(NO_SECURE),false)
